[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'


[project]
name            = 'hockeygameclock'
version         = '1.0.0'
description     = 'Nice hockey game clock for timekeepers.'
authors         = [{name = 'Kilian Märkl'}]
maintainers     = [{name = 'Kilian Märkl'}]
license         = {file = "LICENSE"}
readme          = "README.md"
requires-python = '>=3.10.10'
dependencies    = ['PySide6==6.4.2']

[project.urls]
repository = 'https://github.com/maerkl24/hockeygameclock'

[project.optional-dependencies]
dev = [
    'isort==5.12.0',
    'black==23.1.0',
    'pylint==2.16.1',
    'mypy==1.0.0',
]
test = [
    'pytest==7.2.1',
    'pytest-cov==4.0.0',
]
doc = [
    'Sphinx==6.1.3',
    'furo==2022.12.7',
    'sphinxcontrib-plantuml==0.24.1',
]


[tool.setuptools]
packages = ['hockeygameclock']


[tool.black]
line-length = 120
#include = '(hockeygameclock|tests)\/.*(\.pyi?|\.ipynb)$'


[tool.pylint.main]
load-plugins = ['pylint.extensions.docparams']
ignored-modules = [
    'PySide6',  # Neened for PySide6 on Linux (GitHub CI)
    'hockeygameclock.frontend.ui',  # Ignore Qt user interface Python files (these are generated files)
]
extension-pkg-whitelist = ['PySide6']

[tool.pylint.format]
max-line-length = 120

[tool.pylint."messages control"]
disable = ['too-many-arguments', 'too-few-public-methods', 'too-many-instance-attributes', 'fixme']

[tool.pylint.parameter_documentation]
default-docstring-type = 'google'


[tool.mypy]
warn_return_any = true

[[tool.mypy.overrides]]
module = 'hockeygameclock.frontend.ui.*'
ignore_missing_imports = true


[tool.isort]
profile = "black"
line_length = 120


[tool.pytest.ini_options]
addopts = "--cov=hockeygameclock"
testpaths = ['tests']
