name: Analysis
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/analysis.yml'
      - 'hockeygameclock/**'
      - 'tests/**'
jobs:
  import:
    name: Import analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -e .[dev]
      - name: Run isort
        run: |
          isort --check hockeygameclock
          isort --check tests
  format:
    name: Format analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -e .[dev]
      - name: Run Black
        run: |
          black --check hockeygameclock
          black --check tests
  static:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -e .[dev]
      - name: Run Pylint
        run: |
          pylint hockeygameclock
          pylint tests
      - name: Run mypy
        run: |
          mypy hockeygameclock
          mypy tests
