name: Documentation
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/documentation.yml'
      - 'docs/**'
      - 'hockeyclock/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -e .[doc]
      - name: Run Sphinx
        run: |
          cd docs
          make html
          cd ..
      - name: Upload html artefact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-html
          path: docs/_build/html
