name: Format 📝
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/format.yml'
      - 'pyproject.toml'
      - 'hockeygameclock/**'
      - 'tests/**'
jobs:
  isort:
    name: Isort
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10 and PDM 2.10.0
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'
          architecture: x64
          version: 2.10.0
      - name: Install hockeygameclock and development tools
        run: pdm install -dG format
      - name: Run isort
        run: |
          pdm run isort --check hockeygameclock
          pdm run isort --check tests
  black:
    name: Black
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10 and PDM 2.4.9
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'
          architecture: x64
          version: 2.4.9
      - name: Install hockeygameclock and development tools
        run: pdm install -dG format
      - name: Run black
        run: |
          pdm run black --check hockeygameclock
          pdm run black --check tests
