name: Generation
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/generation.yml'
      - 'qt_ui/**'
jobs:
  test:
    name: Qt UI Python generation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -e .
      - name: Run pyside6-uic and pyside6-rcc
        run: |
          pyside6-uic qt_ui/main_window.ui -o hockeygameclock/frontend/ui/main_window.py --from-imports
          pyside6-rcc qt_ui/resources.qrc -o hockeygameclock/frontend/ui/resources_rc.py
