name: Linting 💡
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/linting.yml'
      - 'pyproject.toml'
      - 'hockeygameclock/**'
      - 'tests/**'
jobs:
  pylint:
    name: Pylint on Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} and PDM 2.4.9
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.4.9
      - name: Install hockeygameclock and development tools
        run: pdm install -dG lint
      - name: Run pylint
        run: |
          pdm run pylint hockeygameclock
          pdm run pylint tests
  mypy:
    name: Mypy on Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} and PDM 2.10.0
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.10.0
      - name: Install hockeygameclock and development tools
        run: pdm install -dG lint
      - name: Run mypy
        run: |
          pdm run mypy hockeygameclock
          pdm run mypy tests
