name: Tests 🧪
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'pyproject.toml'
      - 'hockeygameclock/**'
      - 'tests/**'
jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} and PDM 2.10.0
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.10.0
      - name: Install hockeygameclock and development tools
        run: pdm install -dG test
      - name: Run pytest
        run: pdm run pytest
