name: Test
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'hockeyclock/**'
      - 'tests/**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -e .[test]
      - name: Run pytest
        run: pytest
